### ISSUE TITLE
salloc does not manage AURORA specific environment variables

### ISSUE THREAD

**Issue by thxst** [henkela/SX-Aurora-Slurm-Plugin#1]

**Comment by thxst** [comment]
Hello,

I've compiled the AURORA GRES plugin with SLURM v. 18.08.1.
'sbatch' and 'srun' work fine on a multi VE system.
If one wants to start an interactive job with 'salloc' none of the AURORA specific environment variables is set:

```
salloc --gres=aurora:1 -n 1 --time=0:5:0
salloc: Granted job allocation 1312
bash-4.2$ printenv | grep AURORA
bash-4.2$ exit
exit
salloc: Relinquishing job allocation 1312
```

My current workaround is using 'srun' starting a shell.
Any ideas why salloc fails in that matter?

Best,
Thomas

**Comment by henkela** [comment]
Hello @thxst, 
I just added a comment to the readme.md that I haven't tested this plugin with 18.08.xx. This shouldn't matter though. I made a quick test on our GPU-partition and there the behavior is the same. I think that's a shortcoming of the gres-plugin in general. 
If I do salloc --gres=gpu:1 Slurm doesn't set CUDA_VISIBLE_DEVICES, SLURM_STEP_GPUS etc. while if I run srun --gres=gpu:1 those variables are set. 
I would have expected that this 
```
if (is_job)
      slurm_env_var = "SLURM_JOB_AURORAS";
```
at least is set within allocation environment. Unfortunately, the next days I don't have enough time to start digging for the route cause. 
Best, 
Andreas

**Comment by henkela** [comment]
@thxst 
FYI: I asked about that on the slurm mailing list.

**Comment by henkela** [comment]
Hello @thxst,
Gres doesn’t support this generally. You have use the srun-command to get those variables set. 
By the way, how should those variables look like for multinode allocations? CUDA_VISIBLE_DEVICES always holds the lndices of the GPUs. For multinode you would need an advanced mapping string or additional variables. Additionally, after calling salloc you end up on the calling node, which is typically a login/frontend node. As far as I know there are no remote calls in Cuda that don’t utilize mpirun, hence srun. 

HTH,
Andreas
